# Generated by Django 3.1.2 on 2020-10-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('weight_liquid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity_of_doses', models.DecimalField(decimal_places=1, max_digits=2)),
                ('gross_bottle_weight', models.DecimalField(decimal_places=1, max_digits=6)),
                ('tare', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
