# Generated by Django 3.1.2 on 2020-10-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightconfig',
            name='quantity_of_doses',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weightconfig',
            name='tare',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weightconfig',
            name='weight_liquid',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
