# Generated by Django 3.1.2 on 2020-10-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_auto_20201025_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightconfig',
            name='weigh_bottle_and_liquid',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
